/*
-----------------------------------------
EXPLORATORY DATA ANALYSIS
-----------------------------------------
*/


--========================================
--Database Exploration:
--========================================

-- Explore all objects in database

SELECT * FROM INFORMATION_SCHEMA.TABLES

-- Explore all columns in the database

SELECT * FROM INFORMATION_SCHEMA.COLUMNS

-- Explore a specific table
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'

--=======================================
-- Dimensions Exploration
--=======================================

/*
Identify unique values (or categories ) in each dimension.
Recognizing how data might be grouped or segmented which is useful for 
later analysis.
*/

-- Explore all countries our customers come from.

SELECT DISTINCT	
	country
FROM dbo.dim_customers

-- Explore all categories 'The major divisions'.

SELECT DISTINCT
	category
FROM dbo.dim_products

--Explore all categories and subcategories 'The major divisions'
SELECT DISTINCT
	category,
	subcategory
FROM dbo.dim_products

--Explore product names
SELECT DISTINCT
	category,
	subcategory,
	product_name
FROM dbo.dim_products
ORDER BY 1,2,3

--=========================================
-- Date exploration
--=========================================

/*
Identify the earliest and latest dates(boundaries).
Understand the scope of the data and timespan.
Useful for time analysis.
*/

-- Find the date of the first and last order.
-- How many years of sales are available.
SELECT
	MIN(order_date) AS first_order,
	MAX(order_date) AS last_order,
	DATEDIFF(year, MIN(order_date), MAX(order_date)) AS years_between,
	DATEDIFF(month, MIN(order_date), MAX(order_date)) AS months_between
FROM dbo.fact_sales

-- Find the youngest and oldest customer
SELECT
	MIN(birthdate) AS oldest_customer,
	DATEDIFF(year, MIN(birthdate),GETDATE()) AS oldest_age,
	MAX(birthdate) AS youngest_customer,
	DATEDIFF(year, MAX(birthdate), GETDATE()) AS youngest_age
FROM dbo.dim_customers

--===============================================
-- Measures Exploration
--===============================================

--Done to calculate key metric of the business.

-- Find total sales.
SELECT 
	SUM(sales_amount) AS total_sales
FROM dbo.fact_sales

-- Find how many items are sold.
SELECT 
	SUM(quantity) AS items_sold
FROM dbo.fact_sales

-- Find the average selling price.
SELECT
	ROUND(AVG(price*1.0),2) AS avg_price
FROM dbo.fact_sales

-- Find the total number of orders.
SELECT
	COUNT( DISTINCT order_number) AS total_orders
FROM dbo.fact_sales

-- Find the total number of products.
SELECT
	COUNT( product_key) AS total_products
FROM dbo.dim_products

-- Find the total number customers
SELECT
	COUNT( customer_key) AS total_customers
FROM dbo.dim_customers

-- Find the total number of customers that has placed an order.
SELECT 
	COUNT(DISTINCT customer_key) customers_ordered
FROM dbo.fact_sales

-- Generate Report that shows all key metrics of the business.
SELECT 
	'Total Sales' AS measure_name,
	SUM(sales_amount) AS measure_value
FROM dbo.fact_sales

UNION ALL

SELECT 
	'Items_sold',
	SUM(quantity) 
FROM dbo.fact_sales

UNION ALL 

SELECT
	'Average selling price',
	AVG(price)
FROM dbo.fact_sales

UNION ALL

SELECT
	'Total number of orders',
	COUNT( DISTINCT order_number) 
FROM dbo.fact_sales

UNION ALL 

SELECT	'Total number of products',
	COUNT( product_key) 
FROM dbo.dim_products

UNION ALL

SELECT
	'Total number of customers',
	COUNT( customer_key) AS total_customers
FROM dbo.dim_customers

UNION ALL

SELECT 
	'Total number of customers ordered',
	COUNT(DISTINCT customer_key) customers_ordered
FROM dbo.fact_sales

--=============================================
-- Magnitude
--=============================================

/*
Compare the measure values by categories.
It helps us understand the importance of different categories.
*/

-- Find total customers by countries.
SELECT 
	country,
	COUNT(customer_key) AS total_customers
FROM dbo.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- Find total customers by gender.
SELECT
	gender,
	COUNT(customer_key) AS total_customers
FROM dbo.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- Find total products by categories.
SELECT
	category,
	COUNT(product_key) AS total_products
FROM dbo.dim_products
GROUP BY category
ORDER BY total_products DESC

-- What is the average cost in each category.
SELECT
	category,
	AVG(cost) AS avg_cost
FROM dbo.dim_products
GROUP BY category
ORDER BY avg_cost DESC

-- What is the total revenue generated by each category.
SELECT
	p.category,
	SUM(f.sales_amount) AS revenue
FROM dbo.fact_sales f
LEFT JOIN dbo.dim_products p
ON p.product_key = f.product_key
GROUP BY category
ORDER BY revenue DESC

-- Find total revenue generated by each customer.
SELECT
	c.customer_key,
	CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
	SUM(f.sales_amount) AS revenue
FROM  dbo.fact_sales f
INNER JOIN dbo.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.customer_key,
	CONCAT(c.first_name, ' ', c.last_name)
ORDER BY revenue DESC

-- What is the distribution of sold items across countries.

SELECT
	c.country,
	SUM(quantity) AS items_sold
FROM dbo.dim_customers c
INNER JOIN dbo.fact_sales f
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY items_sold DESC

--===========================
-- Ranking
--===========================

-- Which 5 products generate the highest revenue?
SELECT TOP 5
	p.product_key,
	p.product_name,
	SUM(f.sales_amount) AS revenue
FROM dbo.fact_sales f
LEFT JOIN dbo.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_key,
	     p.product_name
ORDER BY revenue DESC

-- What are the 5 worst performing products in terms of sales?
SELECT TOP 5
	p.product_key,
	p.product_name,
	SUM(f.sales_amount) AS revenue
FROM dbo.fact_sales f
LEFT JOIN dbo.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_key,
	     p.product_name
ORDER BY revenue ASC

-- using window functions
SELECT
	*
FROM ( SELECT 
		p.product_key,
		p.product_name,
		SUM(f.sales_amount) AS revenue,
		RANK() OVER ( ORDER BY SUM(f.sales_amount) ASC) AS rank_product
FROM dbo.fact_sales f
LEFT JOIN dbo.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_key,
		p.product_name
) t WHERE rank_product <=5

-- Find top 10 customers who have generated the highest revenue.


SELECT TOP 10
	c.customer_key,
	CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
	SUM(f.sales_amount) AS revenue
FROM  dbo.fact_sales f
INNER JOIN dbo.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.customer_key,
	CONCAT(c.first_name, ' ', c.last_name)
ORDER BY revenue DESC

-- the 3 customers with fewest orders placed.
SELECT TOP 3
	c.customer_key,
	CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
	COUNT(DISTINCT order_number) AS orders_placed
FROM  dbo.fact_sales f
INNER JOIN dbo.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.customer_key,
	CONCAT(c.first_name, ' ', c.last_name)
ORDER BY orders_placed 
